services:
  - type: web
    name: mld-live
    env: node
    plan: free
    branch: main
    buildCommand: |
      apt-get update && \
      apt-get install -y wget gnupg2 libx11-xcb1 libxcomposite1 libxcursor1 \
      libxdamage1 libxi6 libxtst6 libnss3 libxrandr2 libatk1.0-0 libcups2 libxss1 \
      libasound2 libpangocairo-1.0-0 libatk-bridge2.0-0 libgtk-3-0 chromium-browser && \
      npm install
    startCommand: node index.js
